kind: NetworkSecurityPolicy
apiVersion: security.devops.gov.bc.ca/v1alpha1
metadata:
  name: kirk-api-external-ingress
spec:
  description: |
    Allow the frontend (web) to receive connections from the Internet.
  source:
    - - ext:network=any
  destination:
    - - app={{ .Values.app_name }}
      - role={{ .Values.web_role }}
      - env={{ .Values.env }}