kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.kong_config.secrets_name }}
stringData:
  {{ .Values.kong_config.secret_key_name }}: |-
    { 
      "gwa_client_id": "{{ .Values.kong_config.gwa_client_id }}",
      "gwa_namespace": "{{ .Values.kong_config.gwa_namespace}}",
      "apikey": "{{ .Values.kong_config.apikey }}",
      "gwa_env": "{{ .Values.kong_config.gwa_env }}" 
    }
type: Opaque
