{{- if .Values.deploy_service_account -}}
kind: Role
apiVersion: authorization.openshift.io/v1
metadata:
  name:  {{ .Values.app_name }}-role
rules:
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - create
      - patch
  - apiGroups:
      - security.devops.gov.bc.ca
    resources:
      - networksecuritypolicies
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete

  - resources:
      - namespaces
      - projects
    verbs:
      - get
  - resources:
      - secrets
      - serviceaccounts
      - pods/exec
      - pods
      - configmaps
      - replicationcontrollers
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources: 
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - authorization.openshift.io
    resources: 
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
{{ end }}