kind: Route
apiVersion: route.openshift.io/v1
metadata:
  labels:
    app: {{ .Values.app_name }}
    env: {{ .Values.env }}
    role: {{ .Values.web_role }}
    name: {{ .Values.app_name }}-rt
  name: {{ .Values.app_name }}-rt
spec:
  port:
    targetPort: {{ .Values.app_port }}-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Values.app_name }}-svc
    weight: 100
  wildcardPolicy: None
