{{- if .Values.deploy_service_account -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.github_actions_sa.name }}
  labels:
    app: {{ .Values.app_name }}
    name: {{ .Values.github_actions_sa.name }}
    env: {{ .Values.env }}
imagePullSecrets:
  - name: {{ .Values.app_image_pull_secret_params.name }}

{{ end }}