kind: NetworkSecurityPolicy
apiVersion: security.devops.gov.bc.ca/v1alpha1
metadata:
  name: {{ .Values.kong_config.aps_nsp_name }}
spec:
  description: |
    allow aps gateway to route traffic to your api
  source:
    - - $namespace={{ .Values.kong_config.kong_test_project_name }}
    - - $namespace={{ .Values.kong_config.kong_prod_project_name }}
  destination:
    - - app={{ .Values.app_name }}
