_format_version: '1.1'
services:
- name: smk-fap-fcp-svc
  plugins: []
  routes:
  - hosts:
    - smk-fap-fcb
    methods:
    - GET
    name: smk-fap-fcp-kong-route
    paths:
    - /
    strip_path: false
    tags:
    - OAS3_import
    - ns.smk-apps
  tags:
  - OAS3_import
  - ns.smk-apps
  url: https://smk-fap-fcb-rt-b16795-dev.apps.silver.devops.gov.bc.ca/